package com.bwei.android_zhangxiaokang20190120.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bwei.android_zhangxiaokang20190120.bean.CarBean;

import com.bwei.android_zhangxiaokang20190120.bean.CarBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig carBeanDaoConfig;

    private final CarBeanDao carBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        carBeanDaoConfig = daoConfigMap.get(CarBeanDao.class).clone();
        carBeanDaoConfig.initIdentityScope(type);

        carBeanDao = new CarBeanDao(carBeanDaoConfig, this);

        registerDao(CarBean.class, carBeanDao);
    }
    
    public void clear() {
        carBeanDaoConfig.clearIdentityScope();
    }

    public CarBeanDao getCarBeanDao() {
        return carBeanDao;
    }

}
